apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  labels:
    app: sso
  name: example-keycloak
  namespace: keycloak
spec:
  db:
    usernameSecret:
      key: username
      name: db-secret
    passwordSecret:
      key: password
      name: db-secret
    port: 5432
    vendor: postgres
    host: postgresql
    poolInitialSize: 2
    poolMaxSize: 3
    url: 'jdbc:postgresql://postgresql.keycloak.svc.cluster.local:5432/keycloak'
    poolMinSize: 2
    database: keycloak
  additionalOptions:
    - name: health-enabled
      value: 'false'
  features:
    enabled:
      - fips
  hostname:
    hostname: fipskeycloak.apps.asaro.az-env1.appeng.rhecoeng.com
  http:
    tlsSecret: cluster-cert
  image: 'quay.io/mpaulgreen/keycloak-fips-pod:21.0.2'
  instances: 1
  transaction:
    xaEnabled: false
  