apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  labels:
    app: sso
  name: example-keycloak
  namespace: keycloak
spec:
  additionalOptions:
    - name: health-enabled
      value: 'false'
  features:
    enabled:
      - fips
  hostname:
    hostname: fipskeycloak.apps.asaro.az-env1.appeng.rhecoeng.com
  http:
    tlsSecret: cluster-cert
  image: 'quay.io/mpaulgreen/keycloak-fips-pod:21.0.2'
  instances: 1